In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
train = pd.read_csv(r'E:\TIANCHI\MOBILE\datasets\train_dataset.csv')

In [5]:
train.head()

用户编码  用户实名制是否通过核实  用户年龄  是否大学生客户  是否黑名单客户  \
0  a4651f98c82948b186bdcdc8108381b4            1    44        0        0   
1  aeb10247db4e4d67b2550bbc42ff9827            1    18        0        0   
2  5af23a1e0e77410abb25e9a7eee510aa            1    47        0        0   
3  43c64379d3c24a15b8478851b22049e4            1    55        0        0   
4  f1687f3b8a6f4910bd0b13eb634056e2            1    40        0        0   

   是否4G不健康客户  用户网龄（月）  用户最近一次缴费距今时长（月）  缴费用户最近一次缴费金额（元）  用户近6个月平均消费值（元）  ...  \
0          0      186                1            99.80          163.86  ...   
1          1        5                1            29.94          153.28  ...   
2          0      145                1            49.90          109.64  ...   
3          0      234                1            99.80           92.97  ...   
4          0       76                1            49.90           95.47  ...   

   当月是否景点游览  当月是否体育场馆消费  当月网购类应用使用次数  当月物流快递类应用使用次数  当月金融理财类应用使用总次数  \
0         1           1          713              0            2740   
1         0           0          414              0            2731   
2         0           0         3391              0               0   
3         1           1          500              0            1931   
4         1           0          522              0              64   

   当月视频播放类应用使用次数  当月飞机类应用使用次数  当月火车类应用使用次数  当月旅游资讯类应用使用次数  信用分  
0           7145            0            0             30  664  
1          44862            0            0              0  530  
2           4804            0            0              1  643  
3           3141            0            0              5  649  
4             59            0            0              0  648  

[5 rows x 30 columns]

In [8]:
train['是否大学生客户'].unique()

array([0, 1], dtype=int64)

In [10]:
train[train['是否大学生客户']==1].shape[0]

186

In [13]:
len(set(train['用户编码']))

50000

In [16]:
train[train['是否大学生客户']==1]['信用分'].mean()

635.6344086021505

In [17]:
train['信用分'].mean()

618.05306

**学生客户只有186人，但是学生的信用分均值高与社会群体17分，所以可以考虑单独设置特征表征是否为学生客户**

In [30]:
train['用户网龄（月）'].describe()

count    50000.000000
mean        96.448680
std         59.176593
min          1.000000
25%         48.000000
50%         94.000000
75%        139.000000
max        288.000000
Name: 用户网龄（月）, dtype: float64

In [28]:
train[train['用户网龄（月）']>1].shape[0]

49985

In [31]:
train[train['用户网龄（月）']>120].shape[0]

17291

In [42]:
train[(train['用户网龄（月）']<12)]['信用分'].mean()

554.0212399540758

In [40]:
train[(train['用户网龄（月）']>12)&(train['用户网龄（月）']<60)]['信用分'].mean()

598.0841305090537

In [35]:
train[(train['用户网龄（月）']>120)& (train['用户网龄（月）']<240)]['信用分'].mean()

641.7438474035743

In [33]:
train[train['用户网龄（月）']>240]['信用分'].mean()

652.202492211838

*上述的是一种规则，使用年份越长，信用分越高*

In [44]:
train[train['是否黑名单客户']==1].shape[0]

2440

In [45]:
train[train['是否黑名单客户']==1]['信用分'].mean()

638.7680327868852

In [46]:
train[train['是否黑名单客户']==0]['信用分'].mean()

616.990306980656

**这就很难受了，黑名单用户的信用均分居然还要高于非黑名单用户**

In [49]:
train[train['是否4G不健康客户']==1].shape[0]

4429

In [50]:
train[train['是否4G不健康客户']==1]['信用分'].mean()

598.0180627681192

In [51]:
train[train['是否4G不健康客户']==0]['信用分'].mean()

620.0002413815804

**4G健康与否很大程度上会影响用户信用分**

In [56]:
train['用户最近一次缴费距今时长（月）'].unique()

array([1, 0], dtype=int64)

In [57]:
train[train['用户最近一次缴费距今时长（月）']==1].shape[0]

35005

In [69]:
# for i in range(50000):
#     if train['缴费用户最近一次缴费金额（元）'][i]>train['用户近6个月平均消费值（元）'][i]:
#         print(train['信用分'][i])
train[(train['缴费用户最近一次缴费金额（元）']>train['用户近6个月平均消费值（元）'])]['信用分'].mean()

616.4071389940508

In [70]:
train[(train['缴费用户最近一次缴费金额（元）']<train['用户近6个月平均消费值（元）'])]['信用分'].mean()

618.4353567834262

**看起来最近一次缴费金额是否大于最近六月平均消费值并不那么重要。**

In [73]:
train['缴费用户当前是否欠费缴费'].unique()

array([0, 1], dtype=int64)

In [76]:
train[train['缴费用户当前是否欠费缴费']==1]['信用分'].mean()

634.2386752950133

In [77]:
train[train['缴费用户当前是否欠费缴费']==0]['信用分'].mean()

617.1555105228716

** 感觉又是和常识相违背的**

In [78]:
train['用户最近一次缴费距今时长（月）'].unique()

array([1, 0], dtype=int64)

** 用户话费敏感度**
 - 只有5个话费敏感度等级。这里为什么有6个分类

In [79]:
train['用户话费敏感度'].unique()

array([3, 1, 2, 5, 4, 0], dtype=int64)

In [80]:
train[train['用户话费敏感度']==0]['信用分'].mean()

588.7333333333333

In [81]:
train[train['用户话费敏感度']==1]['信用分'].mean()

627.41327676566

In [82]:
train[train['用户话费敏感度']==2]['信用分'].mean()

628.7496828340002

In [83]:
train[train['用户话费敏感度']==3]['信用分'].mean()

626.188271905086

In [84]:
train[train['用户话费敏感度']==4]['信用分'].mean()

617.1601974122982

In [85]:
train[train['用户话费敏感度']==5]['信用分'].mean()

597.301033097379

In [87]:
train['当月网购类应用使用次数'].describe()

count     50000.000000
mean       1148.815260
std        3992.957952
min           0.000000
25%          18.000000
50%         250.000000
75%         932.000000
max      234336.000000
Name: 当月网购类应用使用次数, dtype: float64

In [90]:
train[train['当月网购类应用使用次数']<18]['当月网购类应用使用次数'].count()

12380

In [91]:
train[(train['当月网购类应用使用次数']<250) & (train['当月网购类应用使用次数']>18)]['当月网购类应用使用次数'].count()

12453

In [92]:
train[(train['当月网购类应用使用次数']>250) & (train['当月网购类应用使用次数']<932)]['当月网购类应用使用次数'].count()

12482

In [93]:
train[train['当月网购类应用使用次数']>932]['当月网购类应用使用次数'].count()

12497

In [96]:
train['近三个月月均商场出现次数'].describe()

count    50000.000000
mean        26.572520
std         32.789251
min          0.000000
25%          1.000000
50%          8.000000
75%         50.000000
max         92.000000
Name: 近三个月月均商场出现次数, dtype: float64

In [98]:
(train['当月网购类应用使用次数'] + train['当月物流快递类应用使用次数'] ).describe()

count     50000.000000
mean       1150.013100
std        3993.660693
min           0.000000
25%          18.000000
50%         251.000000
75%         934.000000
max      234336.000000
dtype: float64

In [101]:
train[(train['当月网购类应用使用次数'] + train['当月物流快递类应用使用次数'])<18]['信用分'].mean()

592.4519961208987

In [107]:
amusing = train['当月网购类应用使用次数'] + train['当月物流快递类应用使用次数']
train[(amusing>18) & (amusing<251)]['信用分'].mean()

623.8280009622324

In [108]:
amusing = train['当月网购类应用使用次数'] + train['当月物流快递类应用使用次数']
train[(amusing>251) & (amusing<934)]['信用分'].mean()

630.1956852995429

In [109]:
train[amusing>934]['信用分'].mean()

625.6243695460731

**飞机类应用的使用次数对信用分影响还是挺大的**

In [114]:
train['当月飞机类应用使用次数'].unique().shape[0]

150

In [123]:
train[train['当月飞机类应用使用次数']>477]['信用分'].describe()

count      7.000000
mean     642.000000
std       23.930455
min      606.000000
25%      626.000000
50%      650.000000
75%      660.000000
max      666.000000
Name: 信用分, dtype: float64

In [125]:
train[train['当月飞机类应用使用次数']<=477]['信用分'].describe()

count    49993.000000
mean       618.049707
std         42.444238
min        422.000000
25%        594.000000
50%        627.000000
75%        649.000000
max        719.000000
Name: 信用分, dtype: float64

**火车类应用使用次数**
 - 这里应该可以化为=0和其它

In [121]:
train['当月火车类应用使用次数'].unique()

array([  0,   2,   1,   3,  46,   4,   5,  18,   6,   9, 115,  12,  22,
         7,   8,  11,  28,  10, 177,  42,  27,  21,  77,  36,  53,  16,
        50,  20, 194,  13,  17, 349,  65,  23, 220,  32,  31, 105,  30,
        83,  52,  24, 308,  44,  64,  14, 123,  15,  48,  93,  72,  25,
       258,  26,  41,  57,  69,  39,  58, 212,  29, 163,  56, 157,  75,
        34,  73, 135, 106,  98, 171,  47,  74,  33, 109,  63, 245, 449,
        40, 226, 116,  88, 126,  61, 130, 118, 257,  62, 100,  91,  60,
       160, 364,  19,  96,  55,  71,  79, 133,  38,  35, 127, 138, 164,
        78, 108, 146, 415,  86, 262, 474,  59, 210, 289,  43, 120,  45,
        51, 260, 176,  49, 119, 155, 195, 152, 103, 197,  68,  90, 121,
       301,  94, 144,  92,  37,  89, 140, 161,  70], dtype=int64)

In [120]:
train['当月火车类应用使用次数'].describe()

count    50000.000000
mean         0.553340
std          7.735913
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        474.000000
Name: 当月火车类应用使用次数, dtype: float64

In [126]:
train[train['当月火车类应用使用次数']>0]['信用分'].mean()

635.9412955465586

In [128]:
train[train['当月火车类应用使用次数']==0]['信用分'].mean()

617.1234588680833

这里可以将连续性数值转化为等级分类

In [110]:
vis = train['当月飞机类应用使用次数']+train['当月火车类应用使用次数']+train['当月旅游资讯类应用使用次数']
vis.describe()

count    50000.000000
mean        20.374880
std        173.220745
min          0.000000
25%          0.000000
50%          0.000000
75%          5.000000
max      13967.000000
dtype: float64

In [129]:
train[vis==0]['信用分'].mean()

611.8077739945387

In [131]:
train[(vis>0) & (vis<=5)]['信用分'].mean()

628.8060613320556

In [133]:
train[vis>5]['信用分'].mean()

626.0176828759696

In [134]:
train['当月旅游资讯类应用使用次数'].describe()

count    50000.000000
mean        19.117120
std        170.074772
min          0.000000
25%          0.000000
50%          0.000000
75%          4.000000
max      13965.000000
Name: 当月旅游资讯类应用使用次数, dtype: float64

In [146]:
train[train['当月旅游资讯类应用使用次数']==0]['信用分'].mean()

612.5754821837202

In [144]:
train[train['当月旅游资讯类应用使用次数']>0]['信用分'].mean()

626.685677485832

In [143]:
train[train['当月旅游资讯类应用使用次数']>0]['当月旅游资讯类应用使用次数'].shape[0]

19410

In [147]:
shopping = train['是否经常逛商场的人']+train['当月是否逛过福州仓山万达']+train['当月是否到过福州山姆会员店']

In [149]:
shopping.unique()

array([1, 0, 2, 3], dtype=int64)

In [150]:
ammusement = train['当月是否看电影']+train['当月是否景点游览']+train['当月是否体育场馆消费']

In [151]:
ammusement.unique()

array([2, 0, 1, 3], dtype=int64)

**自定义分箱操作**

In [ ]:
sensity = np.array([[0],[1],[2],[3],[4],[5]])
train['用户话费敏感度'] = 